version: "3.8"

include:
  - docker-compose/csjbad.yaml
  - docker-compose/csjbad-runner.yaml

networks:
  web:
    external: true
    name: traefik_web
  mariadb:
    name: mariadb
    external: true
