name: Docker Image CI

env:
  BACKEND_URL: ${{ vars.BACKEND_URL }}
  BACKEND_API_URL: ${{ vars.BACKEND_API_URL }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry.jalbrecht.fr/csjbad-front:latest
          no-cache: true
          build-args: |
            "BACKEND_URL=${{ vars.BACKEND_URL }}"
            "BACKEND_API_URL=${{ vars.BACKEND_API_URL }}"
