name: Docker Image CI

env:
  BACKEND_URL: ${{ vars.BACKEND_URL }}
  BACKEND_API_URL: ${{ vars.BACKEND_API_URL }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.jalbrecht.fr
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          build-args: |
            "BACKEND_URL=${{ vars.BACKEND_URL }}"
            "BACKEND_API_URL=${{ vars.BACKEND_API_URL }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: registry.jalbrecht.fr/csjbad-front:latest
